version: 0.0
os: linux

files:
  - source: s3://angular-site-first-12/nodejs
    destination: /var/www/html

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 644

hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
