version: 0.0
os: linux

files:
  - source: s3://angular-site-first-12/nodejs
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: beforeInstall.sh
      timeout: 100
  ApplicationStart:
    - location: applicationStart.sh
      timeout: 100
